[control_plane]
rmq01 ansible_host={{ rmq01 }} ansible_user="{{ ansible_user }}" ansible_connection=local

[workers]
worker-1 ansible_host="{{ worker 1 }}" ansible_user="{{ ansible_user }}"
worker-2 ansible_host="{{ worker 2 }}" ansible_user="{{ ansible_user }}"
worker-3 ansible_host="{{ worker 3 }}" ansible_user="{{ ansible_user }}"
worker-4 ansible_host="{{ worker 4 }}" ansible_user="{{ ansible_user }}"

[k8s_cluster:children]
control_plane
workers
